Fix TestApp Make scripts for Xcode 16 (#444)
Xcode 16 build introduce new issues while building TestApp target of DeviceAgent.iOS.
error: Failed to read Info.plist of app DeviceAgent.iOS/build/ipa/TestApp/Build/Products/Debug-iphoneos/TestApp.app: The operation couldn’t be completed. (XCBUtil.PropertyListConversionError error 1.) (in target 'TestApp' from project 'DeviceAgent')

This issue was related to usage TARGET_BUILD_DIR in xcodebuild parameters. This PR removes this parameter. The derived data path will be used instead.